

build:
	docker build -t helloworld .

images:
	docker images

ps:
	docker ps -a

run:
	docker run --name helloworld helloworld

run2:
	docker run --name helloworld docker/whalesay

clean:
	docker rm helloworld
	docker rmi helloworld