
##
## Kubernetes 
##

start:
	minikube start 

stop:
	minikube stop

api:
	kubectl proxy --port=8080 

list:
	kubectl get pods

list-all:
	kubectl get pods --all-namespaces

cluster:
	kubectl cluster-info

gui:
	minikube dashboard

nodes:
	kubectl get nodes

docker-env:
	minikube docker-env

docker-set:
	# Run this:
	# eval $(minikube docker-env)
	
docker-unset:
	# Run this:
	# eval $(minikube docker-env -u)

docker-images:
	docker images

deploy-list:
	kubectl get deployments


	





